config/routes.rb
Rails.application.routes.draw do
  #get 'contacts/new'
  #get 'posts/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/top_next', to: 'static_pages#next'
  get '/users', to: 'users#new'
  get '/gest_user', to: 'sessions#gest_user'
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notifications, only: :index
  resources :users
  resources :posts do
    resources :comments, only: %i[create edit update destroy]
  end

  resources :posts do
    resources :likes, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
    @post.create_notification_like!(current_user)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user.already_likes?(post) %>
        <%= link_to post_like_path(post_id: post.id, id: post.id), method: :delete, remote: true  do %>
                <span class="like-text">いいね!</span> <i class="fa fa-heart unlike-btn"></i>
        <% end %>
<% else %>
        <%= link_to post_likes_path(post_id: post.id), method: :post, remote: true do %>
                <span class="like-text">いいね!</span><i class="fa fa-heart like-btn"></i>
        <% end %>
<% end %>

<span class="like-count"><%= post.likes.count %></span>

app/views/likes/create.js.erb
$('#likes_buttons').html("<%= j(render partial: 'likes/like', locals: { post: @post }) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons').html("<%= j(render partial: 'likes/like', locals: { post: @post }) %>");