config/routes.rb
Rails.application.routes.draw do
  #get 'contacts/new'
  #get 'posts/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/top_next', to: 'static_pages#next'
  get '/users', to: 'users#new'
  get '/gest_user', to: 'sessions#gest_user'
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notifications, only: :index
  resources :users
  resources :posts do
    resources :comments, only: %i[create edit update destroy]
  end

  resources :posts do
    resources :likes, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: true }, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }
  has_secure_password
  has_one_attached :image
  validate :image_size

  #ランダムな文字列作
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  #渡された文字列をハッシュ化
  def self.digest(string)
    BCrypt::Password.create(string)
  end

  #ハッシュ化した文字列をDBに保存
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #渡された文字列がremember_digestと一致するか？
  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #remember_digestをDBから消す
  def forget
    update_attribute(:remember_digest, nil)
  end

  #画像の検証
  def image_size
    return unless image.attached?

    if image.blob.byte_size > 10.megabytes
      image = nil
      errors.add(:image, '10MB以下にしてください')
    elsif !image?
      image = nil
      errors.add(:image, 'ファイルタイプが無効です')
    end
  end

  #投稿に対していいねしたかどうか
  def already_likes?(post)
    likes.exists?(post_id: post.id)
  end

  def image?
    %w[image/jpg image/jpeg image/gif image/png].include?(image.blob.content_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy]
  before_action :gest_user_invalid, only: [:update]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]

  def show
    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    unless @user.image.attached?
      image_path = Rails.root.join('app/assets/images/user_default.png')
      @user.image.attach(io: File.open(image_path), filename: 'user_default.png')
    end
    if @user.save
      log_in @user
      flash[:success] = 'ようこそ Ssへ'
      redirect_to top_next_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザー設定を更新しました'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def gest_user_invalid
    redirect_to root_path if current_user.email == 'gest_user@user.com'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p class="h2">プロフィール</p>
<%= form_with(model: @user, local: true) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation, 'Confirmation' %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :image, 'プロフィール画像'%>
    <%= f.file_field :image, class: "form-control" %>
    </div>

    <%= f.submit '更新', class: "btn btn-info form-control"%>
<% end%>

app/views/users/new.html.erb
<div class="row justify-content-center">
    <div class="col-sm-3">
        <p class="h2 mb-5 heading-text">新規登録</p>
    </div>
</div>

<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "※必須" %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder: "※必須" %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "6文字以上にしてください" %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "6文字以上にしてください"%>
    </div>

    <div class="form-group">
        <%= f.label :image, 'プロフィール画像'%>
        <div class="custom-file">
            <%= f.label :image, 'クリック', class: "custom-file-label"%>
            <%= f.file_field :image, class: "custom-file-input" %>
        </div>
    </div>


    <div class="form-group text-center">
        <%= f.submit 'アカウントを作成', class: "btn btn-info mt-4"%>
    </div>
<% end %>

app/views/users/show.html.erb
<%# プロフィール画像　%>
<div class="row">
    <div class="col-sm-1">
        <%= image_tag @user.image, size: '100x100', class: "rounded-circle" %>
    </div>
    <div class="col m-auto pl-5">
        <div class="user-name">
            <%= @user.name %>
        </div>
    </div>
    <% if current_user == @user %>
    <div class="col m-auto text-right">
        <%= link_to edit_user_path do %>
            <i class="fa fa-cog fa-2x setting-icon"></i>
        <% end%>
    </div>
    <% end %>
</div>


<div class="row justify-content-center mt-5 mb-5">
    <div class="col-sm-5">
        <p class="h2 heading-text">投稿したポートフォリオ</p>
    </div>
</div>

<% if @user.posts.any? %>
    <%= render @posts %>
<% else %>
    <p>まだポートフォリオを投稿していません</p>
    <%= link_to '早速投稿してみる', new_post_path %>
<% end %>