config/routes.rb
Rails.application.routes.draw do
  #get 'contacts/new'
  #get 'posts/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/top_next', to: 'static_pages#next'
  get '/users', to: 'users#new'
  get '/gest_user', to: 'sessions#gest_user'
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notifications, only: :index
  resources :users
  resources :posts do
    resources :comments, only: %i[create edit update destroy]
  end

  resources :posts do
    resources :likes, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validates :discription, presence: true
  default_scope -> { order(created_at: :desc) }
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  #いいねの通知作成
  def create_notification_like!(current_user)
    temp = Notification.where(['visiter_id = ? and visited_id = ? and post_id = ? and action = ?', current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = Notification.new(
        post_id: id,
        visited_id: user_id,
        visiter_id: current_user.id,
        action: 'like'
      )
      notification.checked = true if notification.visiter_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  #コメントの通知作成
  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).uniq
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  #通知作成
  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = Notification.new(
      post_id: id,
      visited_id: visited_id,
      visiter_id: current_user.id,
      comment_id: comment_id,
      action: 'comment'
    )
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end

  #タグの保存
  def save_tags(tag_list)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - tag_list
    new_tags = tag_list - current_tags

    old_tags.each do |old_tag|
      self.tags.delete Tag.find_by(tag_name: old_tag)
    end

    new_tags.each do |new_tag|
      post_new_tag = Tag.find_or_create_by(tag_name: new_tag)
      self.tags << post_new_tag
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create edit update destroy]
  before_action :set_post, only: %i[destroy edit update]
  #before_action :correct_user, only: [:edit, :update]

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:tag_ids].split(',')
    if @post.save
      @post.save_tags(tag_list)
      flash[:success] = '投稿しました'
      redirect_to current_user
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました'
    redirect_to current_user
  end

  def edit
    @tag_list = @post.tags.pluck(:tag_name).join(',')
  end

  def update
    if @post.update(post_params)
      flash[:success] = '投稿を更新しました'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.includes(:tags, images_attachments: :blob).find(params[:id])
    @user = @post.user
    @comments = @post.comments.includes(user: { image_attachment: :blob })
    @like = Like.new
    @comment = current_user.comments.new if logged_in?
  end

  def index
    @posts = Post.includes(:liked_users).sort { |a, b| b.liked_users.size <=> a.liked_users.size }
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(5)
  end

  private

  def post_params
    params.require(:post).permit(:title, :discription, :github_url, :app_url, :category_id, images: [])
  end

  #def correct_user
  #  @user = User.find(params[:id])
  #  redirect_to root_url unless current_user?(@user)
  #end

  #def correct_user
  #  @post = Post.find(params[:id])
  #  @user = @post.user
  #  redirect_to root_url unless current_user == @user
  #end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="card mb-5 back-color">
    <div class="card-img-top">
        <% if post.images.attached? %>
            <% image = post.images[0] %>
            <%= image_tag image, width: '100%', height: '100%' %>
        <% end %>
    </div>　
    <%= link_to post_path(post), class: "link_to_color" do %>
        <div class="card-body">
            <%= image_tag post.user.image, size: '40x40', class: 'rounded_circle', class: "mr-2 card-title" %>
            <%= post.user.name %>
            <h5 class="card-subtitle mr-60-ml-60 mt-2"><%= post.title %></h5>
            <div class="mt-2 mr-60-ml-60">
                <%= string_extraction_limit(post.discription, 200 )%>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/edit.html.erb
<div class="row justify-content-center">
    <div class="col-sm-4">
        <p class="h2 heading-text">ポートフォリオ編集</p>
    </div>
</div>

<%= form_with(model: @post, local: true, class:"mb-5") do |f| %>
    <%= render "shared/error_messages", object: f.object%>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
    </div>

    <div class="form-group">
        <%= f.label :category_id, "カテゴリ", class: "mt-4"%>
        <%= f.select :category_id, Category.all.map { |o| [o.name, o.id]}, class: "form-control"%>
    </div>

    <div class="form-group mt-5">
        <%= f.label :tag_ids, "タグ" %>
        <%= f.text_field :tag_ids, value: @tag_list, class: "form-control", placeholder: "複数タグをつける際は`,`で区切ってください"%>
    </div>

    <div class="form-group mb-4 mt-4">
        <%= f.label :discription %>
        <%= f.text_area :discription, class: "form-control form-control-lg", row: "20" %>
    </div>

    <div class="form-group mt-5">
        <%= f.label :images, 'イメージ画像' %>
        <%= f.file_field :images, multiple: true, class: "form-control-file" %>
    </div>

    <div class="form-group mt-4">
        <%= f.label :github_url %>
    <%= f.url_field :github_url, class: "form-control" %>
    </div>

    <div class="form-group mt-4">
        <%= f.label :app_url %>
        <%= f.url_field :app_url, class: "form-control"%>
    </div>

    <div class="form-group mt-5">
        <%= f.submit '更新', class: "btn btn-info form-control"%>
    </div>
<% end %>

app/views/posts/index.html.erb
<p class="h2">いいねランキング</p>
<% @posts.each do |post| %>
    <%= post.id %>
    <%= post.title%>
<% end %>

app/views/posts/new.html.erb
<div class="row justify-content-center">
    <div class="col-sm-3">
        <p class="h2 mb-5 heading-text">新規投稿</p>
    </div>
</div>
<%= form_with(model: @post, local: true) do |f| %>
    <%= render "shared/error_messages", object: f.object%>

    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "※必須" %>
    </div>

    <div class="form-group mt-5">
        <%= f.label :category_id, "カテゴリ"%>
        <%= f.select :category_id, Category.all.map { |o| [o.name, o.id]}, class: "form-control"%>
    </div>

    <div class="form-group mt-5">
        <%= f.label :tag_ids, "タグ" %>
        <%= f.text_field :tag_ids, class: "form-control", placeholder: "複数タグをつける際は`,`で区切ってください"%>
    </div>

    <div class="form-group mb-4 mt-5">
        <%= f.label :discription %>
        <%= f.text_area :discription, class: "form-control", rows: "3", placeholder: "※必須
機能や使用技術を書くと検索してもらいやすくなります" %>
    </div>

    <div class="form-group mt-5">
        <%= f.label :images, 'イメージ画像' %>
        <%= f.file_field :images, multiple: true, class: "form-control-file" %>
    </div>

    <div class="form-group mt-5">
        <%= f.label :github_url %>
    <%= f.url_field :github_url, class: "form-control" %>
    </div>

    <div class="form-group mt-5">
        <%= f.label :app_url %>
        <%= f.url_field :app_url, class: "form-control"%>
    </div>

    <div class="form-group mt-5">
        <%= f.submit '投稿', class: "btn btn-info form-control mb-5"%>
    </div>
    
<% end %>

app/views/posts/show.html.erb
<%# 投稿内容　%>
<div class="row border-bottom-5">
    <div class="col">
        <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.image, size: '80x80', class: 'rounded-circle mr-3'%>
            <span class="user-name"><%= @post.user.name %></span>
        <% end %>
    </div>

    <div class="col text-right m-auto">
        <% if current_user?(@user) %>
            <%= link_to edit_post_path(@post), class:"mr-2" do %>
                <i class="fa fa-edit edit"></i>
            <% end %>
            <%= link_to @post, method: :delete, data: { confirm: "この投稿を削除しますか？"} do %>
                <i class="fa fa-trash trash"></i>
            <% end %>
        <% end %>
    </div>
</div>

<div class="row mt-5 mb-2">
    <div class="col-sm-3 ">
        <p class="h3 heading-text">アプリ名</p>
    </div>
</div>
<div class="title">
    <p><%= @post.title %></p>
</div>
<% if @post.tags.present? %>
    <div class="row mb-3">
        <div class="col-sm-3">
            <p class="h3 heading-text">タグ</p>
        </div>
    </div>
    <div class="tag mb-3">
        <% @post.tags.each do |tag| %>
            <span class="mr-2"><%= tag.tag_name %></span>
        <% end %>
    </div>
<% end %>

<div class="row mb-2">
    <div class="col-sm-3">
        <p class="h3 heading-text">概要</p>
    </div>
</div>
<div class="mb-3">
    <%= safe_join(@post.discription.split("\n"), tag(:br)) %>
</div>

<% if @post.github_url.present? %>
    <div class="row mb-3">
        <div class="col-sm-3">
            <p class="h3 heading-text">GitHub</p>
        </div>
    </div>
    <div class="mb-3">
        <%= link_to @post.github_url, @post.github_url, target: :_blank, rel: "noopener noreferrer" %>
    </div>
<% end %>

<% if @post.app_url.present? %>
    <div class="row mb-3">
        <div class="col-sm-3">
            <p class="h3 heading-text">App URL</p>
        </div>
    </div>
    <div class="mb-3">
        <%= link_to @post.app_url, @post.app_url, target: :_blank, rel: "noopener noreferrer" %>
    </div>
<% end %>

<%# イメージ画像表示　%>
<% if @post.images.present? %>
    <div class="row mb-4">
        <div class="col-sm-3">
            <p class="h3 heading-text">イメージ</p>
        </div>
    </div>
    <% i = 0 %>
    <div id="example-2" class="carousel slide" data-ride="carousel" style="width:100%, heiht:100%">
        <div class="carousel-inner">
            <% @post.images.each do |image| %>
                <% if i == 0 %>
                <div class="carousel-item active">
                    <%= image_tag(image) %>
                </div>
                <% else %>
                <div class="carousel-item">
                    <%= image_tag(image) %>
                </div>
                <% end %>
                <% i += 1 %>
            <% end %>
            <a class="carousel-control-prev" href="#example-2" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#example-2" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
<% end %>

<%# いいね %>
<% if logged_in?%>
    <div class="row mt-5 mb-5">
        <div class="col-sm-3 offset-sm-2 text-center">
            <div id="likes_buttons">
                <%= render partial: 'likes/like', locals: { post: @post } %>
            </div>
        </div>
        <div class="col-sm-2 offset-sm-2 text-center">
            <%= link_to "https://twitter.com/intent/tweet?url=#{ request.url }&text=#{@user.name}の#{@post.title}を見てみる", class: "twitter-link" do %>
                <%= fa_icon("twitter")%>Tweet
            <% end%>
        </div>
    </div>
<% end %>

<%# コメントフォーム%>
<div class="row pl-2 justify-content-center">
    <div class="col-sm-3">
        <p class="h3 mt-3 mb-4 heading-text">コメント</p>
    </div>
</div>
<% if logged_in? %>
    <%= form_with(model: [@post, @comment], method: :post, local: :true, class:"mb-4" ) do |f| %>

        <div class="comment-area">
            <%= f.text_area :body, placeholder: "コメントする", class: "form" %>
        </div>

        <%= f.hidden_field :post_id, value: @post.id %>
        <div class="row mt-2">
            <div class="col-sm-8 ml-3 text-right">
                <%= f.submit "投稿", class: "comment-btn"%>
            </div>    
        </div>
    <% end %>
<% else %>
    <p>ログインしてコメントする</p>
<% end %>

<%# コメント一覧　%>
<% @comments.each do |comment|%>
        <div class="row mb-2">
            <div class="col m-1">
                <%= image_tag comment.user.image, size: '40x40' %>
                <%= comment.user.name%>
            </div>
            <% if current_user %>
                <% if current_user?(comment.user) %>
                    <%= link_to edit_post_comment_path(@post.id, comment.id), class: "mr-2" do %>
                        <i class="fa fa-edit edit mt-3"></i>
                    <% end %>
                    <%= link_to post_comment_path(@post.id, comment.id ), method: :delete, data: { confirm: "このコメントを削除しますか？" }, class: "mr-4"  do %>
                        <i class="fa fa-trash trash mt-3"></i>
                    <% end %>
                <% end %>
            <% end %>
        </div>
        <div class="pl-5 mb-5 border border-info rounded-lg">
            <%= safe_join(comment.body.split("\n"), tag(:br)) %>
        </div>
<% end %>