config/routes.rb
Rails.application.routes.draw do
  #get 'contacts/new'
  #get 'posts/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/top_next', to: 'static_pages#next'
  get '/users', to: 'users#new'
  get '/gest_user', to: 'sessions#gest_user'
  root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :notifications, only: :index
  resources :users
  resources :posts do
    resources :comments, only: %i[create edit update destroy]
  end

  resources :posts do
    resources :likes, only: %i[create destroy]
  end

  resources :contacts, only: %i[new create]
end

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
    <div class="row mt-4">
        <div class="col-sm-2 text-center offset-5">
            <span>Ss&nbsp;2021</span>
        </div>
        <div class="col-sm-2 align-self-center offset-3">
            <%= link_to 'お問い合わせ', new_contact_path, class: "contact"%>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
        <span>Yuki&nbsp;Okui</span>
        </div>
    </div>
</footer>
<%#
<p class="mb-3">2021&nbsp;Ss</p>
    <p>Yuki&nbsp;Okui</p>
    <div>
    <p>お問い合わせはこちら</p>
    </div>
=%>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light p-3 ">
      <a class="navbar-brand" href="/"><strong class="logo-text">Ss</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
              <li class="nav-item"><%= link_to '検索' , top_next_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to '新規投稿' , new_post_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'ユーザー' , user_path(current_user), class: "nav-link" %></li>
              <li class="nav-item">
                  <% if unchecked_notifications.any?%>
                    <%= link_to notifications_path, class: "nav-link" do %>
                      <span>通知</span>
                      <i class="fa fa-circle new-notification-color"></i>
                    <% end %>
                  <%else%>
                    <%= link_to '通知', notifications_path, class: "nav-link"%>
                  <% end %>
              </li>
              <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
              <li class="nav-item"><%= link_to 'ゲストログイン', gest_user_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to '新規登録', new_user_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'ログイン', login_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-NLVNX3QN2M"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-NLVNX3QN2M');
    </script>
    <title>Ss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="bg-thin-blue">
    <%= render 'layouts/header'%>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <div id="wrapper">
      <div class='container mt-5'>
        <%= yield %>
      </div>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>